<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li__tab-link col-sm-2</name>
   <tag></tag>
   <elementGuidId>0553db28-0972-4090-ab09-fa68e2b86a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.tab-link.col-sm-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div[2]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;발령사항&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>73d055f0-9728-49d5-adbd-91db19bf8b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-link col-sm-2</value>
      <webElementGuid>d67171e9-1350-4a46-bd6a-c4aac2c9812d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>tab-1</value>
      <webElementGuid>e8693142-98e5-4bec-9afc-86a895a8a39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>발령사항</value>
      <webElementGuid>c1864d6d-02b2-4262-9d4b-de58c5deb1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/section[@id=&quot;content&quot;]/div[@class=&quot;box-style&quot;]/ul[@class=&quot;tabs&quot;]/li[@class=&quot;tab-link col-sm-2&quot;]</value>
      <webElementGuid>d7d4e8fb-0fc9-43f5-8ea6-9a93a2ef48a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div[2]/ul/li</value>
      <webElementGuid>aaf79349-df2f-4cb0-af41-a91665456077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인결함관리'])[1]/following::li[1]</value>
      <webElementGuid>61e6cb0c-f31d-4778-a1c5-af20bf0479cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='경력'])[2]/preceding::li[1]</value>
      <webElementGuid>fbe56950-48a1-47e5-8020-ce4ed8a5fd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='성장'])[2]/preceding::li[2]</value>
      <webElementGuid>2047e68c-215d-47fc-b335-e4063b5f4000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='발령사항']/parent::*</value>
      <webElementGuid>ee1390a6-b56b-4881-94cf-907a6b91bc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>8be90582-31b4-4c75-bae8-0ec467b587bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '발령사항' or . = '발령사항')]</value>
      <webElementGuid>8461bae2-1c0c-45c5-bc77-c5415435424b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
